[package]
name = "stealth_game"
version = "0.1.0"
authors = ["Mikkel Erfurth Gaba <201809037@post.au.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"