[package]
name = "stealth_game"
version = "0.1.1"
authors = ["Gabaa <7581436+Gabaa@users.noreply.github.com>"]
edition = "2021"

[dependencies]
bevy = "0.10.0"
nalgebra = { version = "0.31.1", features = ["mint"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
